apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: kindeh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: alexandrepaulkouame/kindeh-discovery-service:latest
          ports:
          - containerPort: 8761